### THIS CONFIGURATION FILES LISTS PARAMETERS FOR THE PRODUCTION OF ANNUAL CLOUD PROBABILITY PRODUCT (SPF)

# INPUT - area of interest
in_area: 
    tiles: "data/uk_20km_grid.gpkg"
    
# INPUT - satellite collections  
in_stac:
    api_url: "https://earth-search.aws.element84.com/v1"
    collection: "sentinel-2-c1-l2a"
    time:
        year: 2024
        start_date: '2024-01-01'
        end_date: '2024-12-31'
    bands_of_interest: ["cloud", "scl"]

# OUTPUT  
out:
    res: 20
    target_crs: 27700
    out_bands: ['cloud_prob', 'valid_count']
    target_dtype: "float32"
    resampling: "nearest"
    out_format: "GeoTIFF" 
    area_name: "Newcastle"

# DASK CONFIG
dask:
    #chunks_size: {'time':40}
    chunks_size: {'time':20, 'x':250, 'y':250}
    flush: True
